In [1]:
import tensorflow as tf
import numpy as np
from __future__ import print_function

In [2]:
from datetime import date
date.today()
# time.today()

datetime.date(2018, 12, 24)

In [3]:
tf.__version__

'1.4.0'

In [4]:
sess = tf.InteractiveSession()

In [5]:
#tensor shaped [2,3] with zeros

x = tf.zeros([2,3])
print(x)
sess = tf.Session()
sess.run(x)

Tensor("zeros:0", shape=(2, 3), dtype=float32)


array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]], dtype=float32)

In [7]:
xx = np.array([[1,2,3],[4,5,6]])
x = tf.convert_to_tensor(xx)
p = tf.zeros_like(x)
print(p)
sess.run(p)

Tensor("zeros_like_1:0", shape=(2, 3), dtype=int64)


array([[0, 0, 0],
       [0, 0, 0]])

In [9]:
yy = tf.ones([2,3])
print(yy)
sess.run(yy)

Tensor("ones:0", shape=(2, 3), dtype=float32)


array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32)

In [12]:
rr = tf.ones([3,2])
five = tf.constant(5,dtype = tf.float32)
ss = tf.multiply(rr,five)
print(ss)
sess.run(ss)


Tensor("Mul_1:0", shape=(3, 2), dtype=float32)


array([[ 5.,  5.],
       [ 5.,  5.],
       [ 5.,  5.]], dtype=float32)

In [13]:
aa = tf.constant([[1,3,5],[4,6,8]],dtype = tf.float32)
print(aa)
sess.run(aa)

Tensor("Const_3:0", shape=(2, 3), dtype=float32)


array([[ 1.,  3.,  5.],
       [ 4.,  6.,  8.]], dtype=float32)

In [15]:
four = tf.constant(4,dtype = tf.int64,shape = [2,3])
sess.run(four)

array([[4, 4, 4],
       [4, 4, 4]])

In [17]:
out = tf.linspace(5.,10.,50)
sess.run(out)

array([  5.        ,   5.10204077,   5.20408154,   5.3061223 ,
         5.40816307,   5.51020432,   5.61224508,   5.71428585,
         5.81632662,   5.91836739,   6.02040815,   6.12244892,
         6.22448969,   6.32653046,   6.4285717 ,   6.53061247,
         6.63265324,   6.734694  ,   6.83673477,   6.93877554,
         7.04081631,   7.14285755,   7.24489784,   7.34693909,
         7.44897938,   7.55102062,   7.65306139,   7.75510216,
         7.85714293,   7.95918369,   8.06122494,   8.16326523,
         8.26530647,   8.36734676,   8.46938801,   8.5714283 ,
         8.67346954,   8.77551079,   8.87755108,   8.97959232,
         9.08163261,   9.18367386,   9.2857151 ,   9.38775539,
         9.48979568,   9.59183693,   9.69387817,   9.79591846,
         9.89795876,  10.        ], dtype=float32)

In [20]:
out = tf.range(10,102,2)
sess.run(out)

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100], dtype=int32)

In [23]:
aa = tf.random_normal([3,2],0,2.)
sess.run(aa)

array([[-0.38483927, -2.28941512],
       [-1.94890487, -0.927746  ],
       [-1.13704002,  0.93428129]], dtype=float32)

In [24]:
aa = tf.random_normal([3,2])
sess.run(aa)

array([[-0.08800367, -0.52028787],
       [ 1.07355666,  1.54521787],
       [ 0.26796958, -0.07958826]], dtype=float32)

In [25]:
aa = tf.random_uniform([3,2])
sess.run(aa)

array([[ 0.03692973,  0.15609443],
       [ 0.77630818,  0.53902626],
       [ 0.13712478,  0.23232067]], dtype=float32)

In [27]:
pp = tf.constant([[1,2],[3,4],[5,6]])
out = tf.random_shuffle(pp)
sess.run(out)

array([[5, 6],
       [1, 2],
       [3, 4]], dtype=int32)

In [32]:
y = tf.random_normal([10,10,3])
sess.run(y)
sess.run(tf.random_crop(y,[5,5,3]))

array([[[  2.45096421e+00,   4.37824696e-01,   1.87011051e+00],
        [  1.10551977e+00,  -2.95844626e+00,   8.73684406e-01],
        [ -6.88425541e-01,  -1.22569108e+00,   1.50447655e+00],
        [ -1.33733660e-01,   6.42922223e-01,  -4.41273153e-01],
        [ -1.39564002e+00,  -1.24029326e+00,   1.79941928e+00]],

       [[  1.89247298e+00,   6.39390767e-01,   1.09996819e+00],
        [  6.12722993e-01,  -1.27205288e+00,   1.02434719e+00],
        [ -7.02020943e-01,  -9.44199979e-01,  -1.06148280e-01],
        [ -1.03746176e+00,  -7.56753862e-01,  -5.22123158e-01],
        [  8.04212630e-01,   1.80359912e+00,  -1.37084270e+00]],

       [[ -2.26859793e-01,   2.21401080e-01,   9.69118536e-01],
        [  1.60928994e-01,   4.07535821e-01,  -2.70516425e-01],
        [  3.71946931e-01,   2.07197595e+00,   7.50473917e-01],
        [  9.29907680e-01,  -8.70076358e-01,  -1.22325629e-01],
        [  1.06657791e+00,   2.00526524e+00,   3.47722143e-01]],

       [[  7.18843222e-01,   6.960