In [1]:
test = "Hello World"

In [3]:
print("Test: " + test)


Test: Hello World


In [4]:
import math

def sigmoid(x):
    
    z = 1./(1.+math.exp(-1.*x))
    
    
    return z

In [6]:
pp = sigmoid(3)
print(pp)

0.9525741268224334


In [7]:
x = [1,2,3]
sigmoid(x)

TypeError: can't multiply sequence by non-int of type 'float'

In [8]:
import numpy as np
x = np.array([1,2,3])
print(np.exp(x))

[  2.71828183   7.3890561   20.08553692]


In [9]:
x = np.array([1,2,3])
print(x*3)

[3 6 9]


In [13]:
import numpy as np

def sig(x):
     
        
        z = 1./(1.+np.exp(-1.*x))
    
    
        return z


In [14]:

tt = np.array([1,2,3])
sig(tt)


array([ 0.73105858,  0.88079708,  0.95257413])

In [19]:
def sigmoid_gradient(x):
    s = sig(x);
    p = 1.-s;
    
    return s*p;

In [20]:
l = np.array([1,2,3])
print(sigmoid_gradient(x))

[ 0.19661193  0.10499359  0.04517666]


In [21]:
def image2vector(image):
    v = image.reshape((image.shape[0]*image.shape[1]*image.shape[2],1))
    return v

In [22]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

In [23]:
print(image2vector(image))

[[ 0.67826139]
 [ 0.29380381]
 [ 0.90714982]
 [ 0.52835647]
 [ 0.4215251 ]
 [ 0.45017551]
 [ 0.92814219]
 [ 0.96677647]
 [ 0.85304703]
 [ 0.52351845]
 [ 0.19981397]
 [ 0.27417313]
 [ 0.60659855]
 [ 0.00533165]
 [ 0.10820313]
 [ 0.49978937]
 [ 0.34144279]
 [ 0.94630077]]


In [24]:
def normalizerows(x):
    x_norm = np.linalg.norm(x,axis=1,keepdims=True)
    x = x/x_norm
    
    return x

In [25]:
x = np.array([
    [0, 3, 4],
    [1, 6, 4]])

In [26]:
print(normalizerows(x))

[[ 0.          0.6         0.8       ]
 [ 0.13736056  0.82416338  0.54944226]]


In [33]:
def softmax(x):
    
    x_exp = np.exp(x);
    x_sum = np.sum(x_exp,axis=1,keepdims=True)
    x_exp = x_exp/x_sum
    return x_exp

In [34]:
x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0]])

In [35]:
print(softmax(x))

[[  9.80897665e-01   8.94462891e-04   1.79657674e-02   1.21052389e-04
    1.21052389e-04]
 [  8.78679856e-01   1.18916387e-01   8.01252314e-04   8.01252314e-04
    8.01252314e-04]]


In [42]:
import time
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]
tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot+=x1[i]*x2[i];
    toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

tic = time.process_time()
outer = np.zeros((len(x1),len(x2)))
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i]*x2[j]
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

tic = time.process_time()
mul = np.zeros(len(x1))
for i in range(len(x1)):
    mul[i] = x1[i]*x2[i]
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

dot = 278
 ----- Computation time = 0.10099999999946263ms
outer = [[ 81.  18.  18.  81.   0.  81.  18.  45.   0.   0.  81.  18.  45.   0.
    0.]
 [ 18.   4.   4.  18.   0.  18.   4.  10.   0.   0.  18.   4.  10.   0.
    0.]
 [ 45.  10.  10.  45.   0.  45.  10.  25.   0.   0.  45.  10.  25.   0.
    0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.]
 [ 63.  14.  14.  63.   0.  63.  14.  35.   0.   0.  63.  14.  35.   0.
    0.]
 [ 45.  10.  10.  45.   0.  45.  10.  25.   0.   0.  45.  10.  25.   0.
    0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.]
 [ 81.  18.  18.  81.   0.  81.  18.  45.   0.   0.  81.  18.  45.   0.
    0.]
 [ 18.   4.   4.  18.   0.  18.   4.  10.   0.   0.  1

In [52]:
import time
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time();
print("dot = " + str(dot) + "\n Computation Time = " + str(1000*(toc-tic))+ "ms")

tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print("dot = " + str(outer) + "\n Computation Time = " + str(1000*(toc-tic))+ "ms")

tic = time.process_time()
ss = np.multiply(x1,x2)
toc = time.process_time()
print("dot = " + str(ss) + "\n Computation Time = " + str(1000*(toc-tic))+ "ms")

W = np.random.rand(3,len(x1))
tic = time.process_time()
pp = np.dot(W,x1)
toc = time.process_time()
print("dot = " + str(pp) + "\n Computation Time = " + str(1000*(toc-tic))+ "ms")

dot = 278
 Computation Time = 0.11200000000011201ms
dot = [[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [63 14 14 63  0 63 14 35  0  0 63 14 35  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
 Computation Time = 0.47599999999992093ms
dot = [81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]
 Computation Time = 0.13599999999991397ms
dot = [ 21.37658326  18.52485091  16.24474258]
 Computation Time = 0.277000000000526

In [53]:
def L1(ycap,y):
    t = abs(ycap-y)
    s = np.sum(t,axis=0,keepdims=True)
    
    return s

In [54]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat,y)))


L1 = [ 1.1]


In [57]:
def L2(ycap,y):
    loss = np.sum(np.dot(ycap-y,ycap-y))
    
    return loss

In [58]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L2(yhat,y)))

L1 = 0.43
